### ISSUE TITLE
Modcfbg

### ISSUE THREAD

**Issue by leojavieracosta** [Winfidonarleyan/mod-cfbg#10]
In member function      'void CFBG::randomRaceMorph(uint8*, uint32*, TeamId, uint8, uint8)':
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:250:80: error: no m     atching function for call to 'CFBG::getRandomRace(<brace-enclosed initializer li     st>)'
                     *race = getRandomRace({ RACE_ORC, RACE_TAUREN, RACE_TROLL }     );
                                                                                     ^
In file included from /home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.c     pp:6:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note: candida     te: 'template<long unsigned int N> uint8 CFBG::getRandomRace(const uint8 (&)[N])     '
     uint8 getRandomRace(const uint8 (&races)[N]);
           ^~~~~~~~~~~~~
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note:   templ     ate argument deduction/substitution failed:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:250:80: note:   mis     matched types 'unsigned char' and 'Races'
                     *race = getRandomRace({ RACE_ORC, RACE_TAUREN, RACE_TROLL }     );
                                                                                     ^
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:259:95: error: no m     atching function for call to 'CFBG::getRandomRace(<brace-enclosed initializer li     st>)'
                     *race = getRandomRace({ RACE_ORC, RACE_TAUREN, RACE_TROLL,      RACE_BLOODELF });
                                                                                                    ^
In file included from /home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.c     pp:6:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note: candida     te: 'template<long unsigned int N> uint8 CFBG::getRandomRace(const uint8 (&)[N])     '
     uint8 getRandomRace(const uint8 (&races)[N]);
           ^~~~~~~~~~~~~
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note:   templ     ate argument deduction/substitution failed:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:259:95: note:   mis     matched types 'unsigned char' and 'Races'
                     *race = getRandomRace({ RACE_ORC, RACE_TAUREN, RACE_TROLL,      RACE_BLOODELF });
                                                                                                    ^
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:264:82: error: no m     atching function for call to 'CFBG::getRandomRace(<brace-enclosed initializer li     st>)'
                     *race = getRandomRace({ RACE_ORC, RACE_TROLL, RACE_BLOODELF      });
                                                                                       ^
In file included from /home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.c     pp:6:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note: candida     te: 'template<long unsigned int N> uint8 CFBG::getRandomRace(const uint8 (&)[N])     '
     uint8 getRandomRace(const uint8 (&races)[N]);
           ^~~~~~~~~~~~~
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note:   templ     ate argument deduction/substitution failed:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:264:82: note:   mis     matched types 'unsigned char' and 'Races'
                     *race = getRandomRace({ RACE_ORC, RACE_TROLL, RACE_BLOODELF      });
                                                                                       ^
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:270:72: error: no m     atching function for call to 'CFBG::getRandomRace(<brace-enclosed initializer li     st>)'
                     *race = getRandomRace({ RACE_TROLL, RACE_BLOODELF });
                                                                        ^
In file included from /home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.c     pp:6:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note: candida     te: 'template<long unsigned int N> uint8 CFBG::getRandomRace(const uint8 (&)[N])     '
     uint8 getRandomRace(const uint8 (&races)[N]);
           ^~~~~~~~~~~~~
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note:   templ     ate argument deduction/substitution failed:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:270:72: note:   mis     matched types 'unsigned char' and 'Races'
                     *race = getRandomRace({ RACE_TROLL, RACE_BLOODELF });
                                                                        ^
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:275:70: error: no m     atching function for call to 'CFBG::getRandomRace(<brace-enclosed initializer li     st>)'
                     *race = getRandomRace({ RACE_ORC, RACE_BLOODELF });
                                                                      ^
In file included from /home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.c     pp:6:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note: candida     te: 'template<long unsigned int N> uint8 CFBG::getRandomRace(const uint8 (&)[N])     '
     uint8 getRandomRace(const uint8 (&races)[N]);
           ^~~~~~~~~~~~~
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note:   templ     ate argument deduction/substitution failed:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:275:70: note:   mis     matched types 'unsigned char' and 'Races'
                     *race = getRandomRace({ RACE_ORC, RACE_BLOODELF });
                                                                      ^
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:291:68: error: no m     atching function for call to 'CFBG::getRandomRace(<brace-enclosed initializer li     st>)'
                     *race = getRandomRace({ RACE_ORC, RACE_TAUREN });
                                                                    ^
In file included from /home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.c     pp:6:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note: candida     te: 'template<long unsigned int N> uint8 CFBG::getRandomRace(const uint8 (&)[N])     '
     uint8 getRandomRace(const uint8 (&races)[N]);
           ^~~~~~~~~~~~~
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note:   templ     ate argument deduction/substitution failed:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:291:68: note:   mis     matched types 'unsigned char' and 'Races'
                     *race = getRandomRace({ RACE_ORC, RACE_TAUREN });
                                                                    ^
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:298:83: error: no m     atching function for call to 'CFBG::getRandomRace(<brace-enclosed initializer li     st>)'
                     *race = getRandomRace({ RACE_ORC, RACE_TAUREN, RACE_BLOODEL     F });
                                                                                        ^
In file included from /home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.c     pp:6:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note: candida     te: 'template<long unsigned int N> uint8 CFBG::getRandomRace(const uint8 (&)[N])     '
     uint8 getRandomRace(const uint8 (&races)[N]);
           ^~~~~~~~~~~~~
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note:   templ     ate argument deduction/substitution failed:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:298:83: note:   mis     matched types 'unsigned char' and 'Races'
                     *race = getRandomRace({ RACE_ORC, RACE_TAUREN, RACE_BLOODEL     F });
                                                                                        ^
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:305:70: error: no m     atching function for call to 'CFBG::getRandomRace(<brace-enclosed initializer li     st>)'
                     *race = getRandomRace({ RACE_ORC, RACE_BLOODELF });
                                                                      ^
In file included from /home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.c     pp:6:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note: candida     te: 'template<long unsigned int N> uint8 CFBG::getRandomRace(const uint8 (&)[N])     '
     uint8 getRandomRace(const uint8 (&races)[N]);
           ^~~~~~~~~~~~~
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note:   templ     ate argument deduction/substitution failed:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:305:70: note:   mis     matched types 'unsigned char' and 'Races'
                     *race = getRandomRace({ RACE_ORC, RACE_BLOODELF });
                                                                      ^
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:340:110: error: no      matching function for call to 'CFBG::getRandomRace(<brace-enclosed initializer l     ist>)'
                     *race = getRandomRace({ RACE_HUMAN, RACE_DWARF, RACE_GNOME,      RACE_NIGHTELF, RACE_DRAENEI });
                                                                                                                   ^
In file included from /home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.c     pp:6:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note: candida     te: 'template<long unsigned int N> uint8 CFBG::getRandomRace(const uint8 (&)[N])     '
     uint8 getRandomRace(const uint8 (&races)[N]);
           ^~~~~~~~~~~~~
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note:   templ     ate argument deduction/substitution failed:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:340:110: note:   mi     smatched types 'unsigned char' and 'Races'
                     *race = getRandomRace({ RACE_HUMAN, RACE_DWARF, RACE_GNOME,      RACE_NIGHTELF, RACE_DRAENEI });
                                                                                                                   ^
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:344:83: error: no m     atching function for call to 'CFBG::getRandomRace(<brace-enclosed initializer li     st>)'
                     *race = getRandomRace({ RACE_HUMAN, RACE_DWARF, RACE_DRAENE     I });
                                                                                        ^
In file included from /home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.c     pp:6:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note: candida     te: 'template<long unsigned int N> uint8 CFBG::getRandomRace(const uint8 (&)[N])     '
     uint8 getRandomRace(const uint8 (&races)[N]);
           ^~~~~~~~~~~~~
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note:   templ     ate argument deduction/substitution failed:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:344:83: note:   mis     matched types 'unsigned char' and 'Races'
                     *race = getRandomRace({ RACE_HUMAN, RACE_DWARF, RACE_DRAENE     I });
                                                                                        ^
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:348:86: error: no m     atching function for call to 'CFBG::getRandomRace(<brace-enclosed initializer li     st>)'
                     *race = getRandomRace({ RACE_DWARF, RACE_NIGHTELF, RACE_DRA     ENEI });
                                                                                           ^
In file included from /home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.c     pp:6:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note: candida     te: 'template<long unsigned int N> uint8 CFBG::getRandomRace(const uint8 (&)[N])     '
     uint8 getRandomRace(const uint8 (&races)[N]);
           ^~~~~~~~~~~~~
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.h:126:11: note:   templ     ate argument deduction/substitution failed:
/home/azerothcore-wotlk/modules/mod-cfbg-master/src/CFBG.cpp:348:86: note:   mis     matched types 'unsigned char' and 'Races'
                     *race = getRandomRace({ RACE_DWARF, RACE_NIGHTELF, RACE_DRA     ENEI });
                                                                                           ^

**Comment by Winfidonarleyan** [comment]
? Module don't support AC, check readme
