### ISSUE TITLE
[BUiLD] failed!

### ISSUE THREAD

**Issue by wowmane** [Winfidonarleyan/mod-cfbg#2]
Hi @Winfidonarleyan 

error build: 

`CFBG.cpp:352:82: error: use of undeclared identifier 'BG_QUEUE_CFBG'; did you mean
      'BG_QUEUE_MAX'?
    if (!sBattlegroundMgr->isTesting() && bgqueue->m_QueuedGroups[thisBracketId][BG_QUEUE_CFBG].empty() && specificQueue->m_QueuedGro...
                                                                                 ^~~~~~~~~~~~~
`

version: https://github.com/azerothcore/azerothcore-wotlk/commit/4a96f4988d7c0fd9763df50b52fd031161508857

**Comment by Winfidonarleyan** [comment]
Oh my god, check general readme
