### ISSUE TITLE
reload conf

### ISSUE THREAD

**Issue by milestorme** [Winfidonarleyan/mod-cfbg#4]
getting console errors on .reload conf
`Module config: Invalid or missing configuration dist file : /home/wowtorn/rocketAC/etc/CFBG.conf.dist
Module config: Verify that the file exists and has '[worldserver]' written in the top of the file!
Module config: Use default settings!

Module config: Invalid or missing configuration file : /home/wowtorn/rocketAC/etc/CFBG.conf
Module config: Verify that the file exists and has '[worldserver]' written in the top of the file!
Module config: Use default settings!`

yes i have CFBG.conf & CFBG.conf.dist in the correct location, i even tryed removing the MIT credits above [worldserver] still says same console error

**Comment by Winfidonarleyan** [comment]
Hm, maybe you changed the encoding in a file, check, please

**Comment by milestorme** [comment]
I downloaded mod-CFBG from azerothcore repo this afternoon, updated the core to latest , everything looked fine just wouldn’t read the conf . is this isolated to me ?

**Comment by milestorme** [comment]
did a fresh core and added only mod-CFBG same error 
`AzerothCore rev. a0e727ce1f9b 2019-08-08 15:21:13 +0700 (master branch) (Unix, Release) (worldserver-daemon) ready...
.reload conf
Re-Loading config settings...

Module config: Invalid or missing configuration file : /home/michael/bin/etc/CFBG.conf
Module config: Verify that the file exists and has '[worldserver]' written in the top of the file!
Module config: Use default settings!

Module config: Invalid or missing configuration file : /home/michael/bin/etc/CFBG.conf
Module config: Verify that the file exists and has '[worldserver]' written in the top of the file!
Module config: Use default settings!`

**Comment by Winfidonarleyan** [comment]
Hah, okay
