### ISSUE TITLE
Delay invite BG

### ISSUE THREAD

**Issue by dante6319** [Winfidonarleyan/mod-cfbg#5]
Before the required number of players is typed, there is a delay before an invite to the BG, a delay in the region of 2-3 minutes

**Comment by Winfidonarleyan** [comment]
This big bg in random system, need rework random bg system or rework in db table world.battleground_template
change min player per team between 5-10

**Comment by dante6319** [comment]
Щас минимум стоит от 3 человек, но делей когда наберется все 6 игроков все равно есть, примерно от 6 до 10 минут.

Это не связанно с OnBeforeUpdate?

**Comment by Winfidonarleyan** [comment]
Я вот себе для теста вот так сделал 
![image](https://user-images.githubusercontent.com/18329778/63963460-48c5d600-cabf-11e9-9ac9-de878769d13e.png)

А вообще посмотри функцию, может всё поймёшь в файле `BattlegroundMgr.cpp`
```cpp
void RandomBattlegroundSystem::Update(uint32 diff)
```

**Comment by dante6319** [comment]
ОООООО СПАСИБО БОЛЬШОЕ

**Comment by Winfidonarleyan** [comment]
Вообще можешь везде поставить 5, там где у меня 1, во 2-ой колонке `MinPlayerPerTeam`

**Comment by dante6319** [comment]
Нене я не подумал что на ас уебищную систему тайминга ожидания БГ сделают, это же нужно быть совсем не умненькими,  извиняюсь за мат кста, я чекал  сами фаилы кросса

**Comment by dante6319** [comment]
Еще раз спасибо

**Comment by Winfidonarleyan** [comment]
Если проблем с этим больше нет, закрой это
